import { IconBook2, IconBrightness, IconDatabaseExport, IconLayout, IconScanEye, IconSettings, IconTarget } from "@tabler/icons-react"

export const overviewData = [
    { id: 1, label: "Total Words", quantity: 320 },
    { id: 2, label: "Learned", quantity: 185 },
    { id: 3, label: "To Review", quantity: 40 },
    { id: 4, label: "This Week", quantity: 20 },
]

export const dailyVocab = [
    {
        id: 1,
        hanyu: "学习",
        pinyin: "xuéxí",
        mean: "Học tập",
        learned: true,
        toReview: false,
    },
    {
        id: 2,
        hanyu: "你好",
        pinyin: "nǐ hǎo",
        mean: "Xin chào",
        learned: true,
        toReview: false,
    },
    {
        id: 3,
        hanyu: "谢谢",
        pinyin: "xièxie",
        mean: "Cảm ơn",
        learned: true,
        toReview: true,
    },
    {
        id: 4,
        hanyu: "再见",
        pinyin: "zàijiàn",
        mean: "Tạm biệt",
        learned: false,
        toReview: false,
    },
    {
        id: 5,
        hanyu: "朋友",
        pinyin: "péngyou",
        mean: "Bạn bè",
        learned: false,
        toReview: false,
    },
    {
        id: 6,
        hanyu: "老师",
        pinyin: "lǎoshī",
        mean: "Giáo viên",
        learned: false,
        toReview: false,
    },
    {
        id: 7,
        hanyu: "学生",
        pinyin: "xuésheng",
        mean: "Học sinh / Sinh viên",
        learned: false,
        toReview: false,
    },
    {
        id: 8,
        hanyu: "学校",
        pinyin: "xuéxiào",
        mean: "Trường học",
        learned: false,
        toReview: false,
    },
    {
        id: 9,
        hanyu: "工作",
        pinyin: "gōngzuò",
        mean: "Công việc / Làm việc",
        learned: false,
        toReview: false,
    },
    {
        id: 10,
        hanyu: "喜欢",
        pinyin: "xǐhuan",
        mean: "Thích",
        learned: false,
        toReview: false,
    },
    {
        id: 11,
        hanyu: "喜欢",
        pinyin: "xǐhuan",
        mean: "Thích",
        learned: false,
        toReview: false,
    },
    {
        id: 12,
        hanyu: "吃饭",
        pinyin: "chīfàn",
        mean: "Ăn cơm / Ăn",
        learned: false,
        toReview: false,
    },
    {
        id: 13,
        hanyu: "喝水",
        pinyin: "hē shuǐ",
        mean: "Uống nước",
        learned: false,
        toReview: false,
    },
    {
        id: 14,
        hanyu: "今天",
        pinyin: "jīntiān",
        mean: "Hôm nay",
        learned: false,
        toReview: false,
    },
    {
        id: 15,
        hanyu: "明天",
        pinyin: "míngtiān",
        mean: "Ngày mai",
        learned: false,
        toReview: false,
    },
    {
        id: 16,
        hanyu: "昨天",
        pinyin: "zuótiān",
        mean: "Hôm qua",
        learned: false,
        toReview: false,
    },
    {
        id: 17,
        hanyu: "现在",
        pinyin: "xiànzài",
        mean: "Bây giờ",
        learned: false,
        toReview: false,
    },
    {
        id: 18,
        hanyu: "时间",
        pinyin: "shíjiān",
        mean: "Thời gian",
        learned: false,
        toReview: false,
    },
    {
        id: 19,
        hanyu: "中国",
        pinyin: "Zhōngguó",
        mean: "Trung Quốc",
        learned: false,
        toReview: false,
    },
    {
        id: 20,
        hanyu: "中文",
        pinyin: "Zhōngwén",
        mean: "Tiếng Trung",
        learned: false,
        toReview: false,
    },
];

export const menuSidebar = [
    { id: 1, label: "Home", href: "/", icon: IconLayout },
    { id: 2, label: "Vocabulary", href: "/vocabulary", icon: IconBook2 },
    { id: 3, label: "Review", href: "/review", icon: IconScanEye },
    { id: 4, label: "Setting", href: "/setting", icon: IconSettings },
]

export const words = [
    {
        id: 1,
        chinese: "学习",
        pinyin: "xuéxí",
        meaning: "Học tập",
        learned: true,
        toReview: false,
        createdAt: "2026-10-04",
    },
    {
        id: 2,
        chinese: "今天",
        pinyin: "jīntiān",
        meaning: "Hôm nay",
        learned: false,
        toReview: true,
        createdAt: "2026-10-04",
    },
    {
        id: 3,
        chinese: "喜欢",
        pinyin: "xǐhuān",
        meaning: "Thích",
        learned: true,
        toReview: false,
        createdAt: "2026-10-03",
    },
    {
        id: 4,
        chinese: "朋友",
        pinyin: "péngyou",
        meaning: "Bạn bè",
        learned: false,
        toReview: true,
        createdAt: "2026-10-03",
    },
    {
        id: 5,
        chinese: "工作",
        pinyin: "gōngzuò",
        meaning: "Công việc",
        learned: false,
        toReview: false,
        createdAt: "2026-10-02",
    },
    {
        id: 6,
        chinese: "你好",
        pinyin: "nǐ hǎo",
        meaning: "Xin chào",
        learned: true,
        toReview: false,
        createdAt: "2026-10-02",
    },
    {
        id: 7,
        chinese: "谢谢",
        pinyin: "xièxie",
        meaning: "Cảm ơn",
        learned: true,
        toReview: false,
        createdAt: "2026-10-01",
    },
    {
        id: 8,
        chinese: "再见",
        pinyin: "zàijiàn",
        meaning: "Tạm biệt",
        learned: true,
        toReview: false,
        createdAt: "2026-10-01",
    },
    {
        id: 9,
        chinese: "吃饭",
        pinyin: "chīfàn",
        meaning: "Ăn cơm",
        learned: false,
        toReview: true,
        createdAt: "2026-09-30",
    },
    {
        id: 10,
        chinese: "喝水",
        pinyin: "hē shuǐ",
        meaning: "Uống nước",
        learned: false,
        toReview: true,
        createdAt: "2026-09-30",
    },
    {
        id: 11,
        chinese: "学校",
        pinyin: "xuéxiào",
        meaning: "Trường học",
        learned: true,
        toReview: false,
        createdAt: "2026-09-29",
    },
    {
        id: 12,
        chinese: "老师",
        pinyin: "lǎoshī",
        meaning: "Giáo viên",
        learned: true,
        toReview: false,
        createdAt: "2026-09-29",
    },
    {
        id: 13,
        chinese: "学生",
        pinyin: "xuéshēng",
        meaning: "Học sinh",
        learned: false,
        toReview: true,
        createdAt: "2026-09-28",
    },
    {
        id: 14,
        chinese: "中国",
        pinyin: "Zhōngguó",
        meaning: "Trung Quốc",
        learned: true,
        toReview: false,
        createdAt: "2026-09-28",
    },
    {
        id: 15,
        chinese: "中文",
        pinyin: "Zhōngwén",
        meaning: "Tiếng Trung",
        learned: false,
        toReview: true,
        createdAt: "2026-09-27",
    },
    {
        id: 16,
        chinese: "语言",
        pinyin: "yǔyán",
        meaning: "Ngôn ngữ",
        learned: false,
        toReview: false,
        createdAt: "2026-09-27",
    },
    {
        id: 17,
        chinese: "时间",
        pinyin: "shíjiān",
        meaning: "Thời gian",
        learned: true,
        toReview: false,
        createdAt: "2026-09-26",
    },
    {
        id: 18,
        chinese: "现在",
        pinyin: "xiànzài",
        meaning: "Bây giờ",
        learned: false,
        toReview: true,
        createdAt: "2026-09-26",
    },
    {
        id: 19,
        chinese: "明天",
        pinyin: "míngtiān",
        meaning: "Ngày mai",
        learned: false,
        toReview: false,
        createdAt: "2026-09-25",
    },
    {
        id: 20,
        chinese: "昨天",
        pinyin: "zuótiān",
        meaning: "Hôm qua",
        learned: true,
        toReview: false,
        createdAt: "2026-09-25",
    },
    {
        id: 21,
        chinese: "家",
        pinyin: "jiā",
        meaning: "Nhà",
        learned: true,
        toReview: false,
        createdAt: "2026-09-24",
    },
    {
        id: 22,
        chinese: "妈妈",
        pinyin: "māma",
        meaning: "Mẹ",
        learned: false,
        toReview: true,
        createdAt: "2026-09-24",
    },
    {
        id: 23,
        chinese: "爸爸",
        pinyin: "bàba",
        meaning: "Bố",
        learned: true,
        toReview: false,
        createdAt: "2026-09-23",
    },
    {
        id: 24,
        chinese: "吃",
        pinyin: "chī",
        meaning: "Ăn",
        learned: false,
        toReview: true,
        createdAt: "2026-09-23",
    },
    {
        id: 25,
        chinese: "喝",
        pinyin: "hē",
        meaning: "Uống",
        learned: false,
        toReview: false,
        createdAt: "2026-09-22",
    },
    {
        id: 26,
        chinese: "看",
        pinyin: "kàn",
        meaning: "Xem / Nhìn",
        learned: true,
        toReview: false,
        createdAt: "2026-09-22",
    },
    {
        id: 27,
        chinese: "听",
        pinyin: "tīng",
        meaning: "Nghe",
        learned: false,
        toReview: true,
        createdAt: "2026-09-21",
    },
    {
        id: 28,
        chinese: "说",
        pinyin: "shuō",
        meaning: "Nói",
        learned: true,
        toReview: false,
        createdAt: "2026-09-21",
    },
    {
        id: 29,
        chinese: "读",
        pinyin: "dú",
        meaning: "Đọc",
        learned: false,
        toReview: true,
        createdAt: "2026-09-20",
    },
    {
        id: 30,
        chinese: "写",
        pinyin: "xiě",
        meaning: "Viết",
        learned: true,
        toReview: false,
        createdAt: "2026-09-20",
    },
]

export const statusFilters = [
    {
        label: "All",
        value: "all",
    },
    {
        label: "Learning",
        value: "learning",
    },
    {
        label: "Learned",
        value: "learned",
    },
    {
        label: "Review",
        value: "review",
    },
]

export const dateFilters = [
    {
        label: "All dates",
        value: "all",
    },
    {
        label: "Today",
        value: "2026-10-04",
    },
    {
        label: "Yesterday",
        value: "2026-10-03",
    },
    {
        label: "Oct 2, 2026",
        value: "2026-10-02",
    },
    {
        label: "Oct 1, 2026",
        value: "2026-10-01",
    },
    {
        label: "Sep 30, 2026",
        value: "2026-09-30",
    },
]

export const settings = [
    {
        title: "Appearance",
        items: [
            {
                label: "Theme",
                href: "/setting/theme",
                description: "System",
                icon: IconBrightness,
            },
        ],
    },
    {
        title: "Learning",
        items: [
            {
                label: "Daily goal",
                href: "/setting/theme",
                description: "20 words per day",
                icon: IconTarget,
            },
        ],
    },
    {
        title: "Data",
        items: [
            {
                label: "Export vocabulary",
                href: "/setting/theme",
                description: "Export your vocabulary data",
                icon: IconDatabaseExport,
            },
        ],
    },
]