import { IconBook2, IconLayout, IconScanEye, IconSettings } from "@tabler/icons-react"



export const overviewData = [
    { id: 1, label: "Total Words", quantity: 320 },
    { id: 2, label: "Learned", quantity: 185 },
    { id: 3, label: "To Review", quantity: 40 },
    { id: 4, label: "This Week", quantity: 20 },
]

export const dailyVocab = [
    {
        id: 1,
        hanyu: "学习",
        pinyin: "xuéxí",
        mean: "Học tập",
        learned: true,
        toReview: false,
    },
    {
        id: 2,
        hanyu: "你好",
        pinyin: "nǐ hǎo",
        mean: "Xin chào",
        learned: true,
        toReview: false,
    },
    {
        id: 3,
        hanyu: "谢谢",
        pinyin: "xièxie",
        mean: "Cảm ơn",
        learned: true,
        toReview: true,
    },
    {
        id: 4,
        hanyu: "再见",
        pinyin: "zàijiàn",
        mean: "Tạm biệt",
        learned: false,
        toReview: false,
    },
    {
        id: 5,
        hanyu: "朋友",
        pinyin: "péngyou",
        mean: "Bạn bè",
        learned: false,
        toReview: false,
    },
    {
        id: 6,
        hanyu: "老师",
        pinyin: "lǎoshī",
        mean: "Giáo viên",
        learned: false,
        toReview: false,
    },
    {
        id: 7,
        hanyu: "学生",
        pinyin: "xuésheng",
        mean: "Học sinh / Sinh viên",
        learned: false,
        toReview: false,
    },
    {
        id: 8,
        hanyu: "学校",
        pinyin: "xuéxiào",
        mean: "Trường học",
        learned: false,
        toReview: false,
    },
    {
        id: 9,
        hanyu: "工作",
        pinyin: "gōngzuò",
        mean: "Công việc / Làm việc",
        learned: false,
        toReview: false,
    },
    {
        id: 10,
        hanyu: "喜欢",
        pinyin: "xǐhuan",
        mean: "Thích",
        learned: false,
        toReview: false,
    },
    {
        id: 11,
        hanyu: "喜欢",
        pinyin: "xǐhuan",
        mean: "Thích",
        learned: false,
        toReview: false,
    },
    {
        id: 12,
        hanyu: "吃饭",
        pinyin: "chīfàn",
        mean: "Ăn cơm / Ăn",
        learned: false,
        toReview: false,
    },
    {
        id: 13,
        hanyu: "喝水",
        pinyin: "hē shuǐ",
        mean: "Uống nước",
        learned: false,
        toReview: false,
    },
    {
        id: 14,
        hanyu: "今天",
        pinyin: "jīntiān",
        mean: "Hôm nay",
        learned: false,
        toReview: false,
    },
    {
        id: 15,
        hanyu: "明天",
        pinyin: "míngtiān",
        mean: "Ngày mai",
        learned: false,
        toReview: false,
    },
    {
        id: 16,
        hanyu: "昨天",
        pinyin: "zuótiān",
        mean: "Hôm qua",
        learned: false,
        toReview: false,
    },
    {
        id: 17,
        hanyu: "现在",
        pinyin: "xiànzài",
        mean: "Bây giờ",
        learned: false,
        toReview: false,
    },
    {
        id: 18,
        hanyu: "时间",
        pinyin: "shíjiān",
        mean: "Thời gian",
        learned: false,
        toReview: false,
    },
    {
        id: 19,
        hanyu: "中国",
        pinyin: "Zhōngguó",
        mean: "Trung Quốc",
        learned: false,
        toReview: false,
    },
    {
        id: 20,
        hanyu: "中文",
        pinyin: "Zhōngwén",
        mean: "Tiếng Trung",
        learned: false,
        toReview: false,
    },
];

export const menuSidebar = [
    { id: 1, label: "Home", href: "/", icon: IconLayout },
    { id: 2, label: "Vocabulary", href: "/vocabulary", icon: IconBook2 },
    { id: 3, label: "Review", href: "/review", icon: IconScanEye },
    { id: 4, label: "Setting", href: "/setting", icon: IconSettings },
]